"""模型接入层：真实 LLM 优先（配置 LLM_* 环境变量），回落 Mock。

- llm_generate_script / build_storyboard：LLM 生成结构化 JSON；未配置或失败时回落 Java Mock 服务
- generate_shot_video：Mock（生产版换模型路由网关：可灵/Seedance/万相 + 自部署 Wan2.2）
- generate_voice / compose_drama：Mock（生产版：TTS 适配器 / FFmpeg Worker 池）
"""
import asyncio
import json
import logging

from . import config, java_client, llm

logger = logging.getLogger("manju.adapters")

SCRIPT_SYSTEM_PROMPT = """你是资深短剧编剧，为竖屏漫剧（漫画风格短剧）写剧本。
输出严格 JSON（不要任何解释文字），Schema：
{
  "title": "剧名",
  "characters": ["角色名1", "角色名2"],
  "totalScenes": 场次数,
  "scenes": [
    {
      "sceneId": "sc-001",
      "location": "场景地点",
      "description": "画面描述（给分镜图生成的提示词素材，30-60字，具体可视觉化）",
      "dialogues": [
        {"character": "角色名", "emotion": "情绪", "text": "台词（口语化，单句≤25字）"}
      ]
    }
  ]
}
要求：3-4个场景；每个场景1-3句台词；台词符合角色人设；剧情有起承转合，结尾留记忆点。"""

STORYBOARD_SYSTEM_PROMPT = """你是分镜师，把剧本场景切分为镜头。
输出严格 JSON（不要任何解释文字），Schema：
{"shots": [
  {
    "shotNo": 1,
    "sceneId": "sc-001",
    "location": "同场景",
    "shotType": "远景|中景|近景|特写",
    "cameraMove": "固定机位|缓慢推近|轻微横移|缓慢拉远",
    "durationSec": 3到7的整数,
    "prompt": "分镜图生成提示词：漫画风格 + 画面内容 + 运镜效果，30-60字"
  }
]}
要求：每个场景2-3个镜头；景别有变化（建立镜头用远景，情绪点用特写）；prompt 与场景 description 一致但更聚焦单画面。"""


async def prepare_assets(drama_id: str, title: str) -> dict:
    """素材准备：角色资产包 + 场景图 + 音色绑定（Mock）。"""
    await asyncio.sleep(0.2)
    return await java_client.post_json(
        f"{config.ASSET_SVC_URL}/api/assets/prepare",
        {"dramaId": drama_id, "title": title},
    )


async def llm_generate_script(drama_id: str, title: str, topic: str) -> dict:
    """剧本生成：真实 LLM 优先，回落 Mock。"""
    if llm.is_configured():
        try:
            user_prompt = f"剧名：《{title}》\n选题/题材：{topic}\n请生成剧本 JSON。"
            script = await llm.chat_json(SCRIPT_SYSTEM_PROMPT, user_prompt)
            script["dramaId"] = drama_id
            # 基本结构校验（生产版：完整 JSON Schema 校验）
            scenes = script.get("scenes", [])
            if not scenes:
                raise ValueError("LLM script has no scenes")
            for sc in scenes:
                assert sc.get("sceneId") and sc.get("dialogues"), f"bad scene: {sc}"
            script["totalScenes"] = len(scenes)
            logger.info("script generated by real LLM: %d scenes", len(scenes))
            return script
        except Exception as e:  # noqa: BLE001
            logger.warning("real LLM script failed, fallback to mock: %s", e)
    await asyncio.sleep(0.3)
    return await java_client.post_json(
        f"{config.SCRIPT_SVC_URL}/api/scripts/generate",
        {"dramaId": drama_id, "title": title, "topic": topic},
    )


async def build_storyboard(drama_id: str, script: dict) -> dict:
    """分镜脚本：真实 LLM 优先，回落 Mock。"""
    if llm.is_configured():
        try:
            user_prompt = "剧本场景如下，请切分镜头：\n" + json.dumps(
                script.get("scenes", []), ensure_ascii=False)
            result = await llm.chat_json(STORYBOARD_SYSTEM_PROMPT, user_prompt)
            shots = result.get("shots", [])
            if not shots:
                raise ValueError("LLM storyboard has no shots")
            # 规范化 shotNo
            for i, s in enumerate(shots, 1):
                s["shotNo"] = i
                s.setdefault("durationSec", 4)
            logger.info("storyboard generated by real LLM: %d shots", len(shots))
            return {"dramaId": drama_id, "shots": shots, "totalShots": len(shots)}
        except Exception as e:  # noqa: BLE001
            logger.warning("real LLM storyboard failed, fallback to mock: %s", e)
    await asyncio.sleep(0.2)
    return await java_client.post_json(
        f"{config.STORYBOARD_SVC_URL}/api/storyboards/generate",
        {"dramaId": drama_id, "scenes": script.get("scenes", [])},
    )


async def generate_shot_video(drama_id: str, shot: dict) -> dict:
    """分镜视频：提交-轮询统一任务模型（Mock，约 1.5s 完成）。

    生产版此函数改为调用模型路由网关：submit(task) -> task_id，
    由网关回调驱动 resume（interrupt 模式），而非节点内轮询。
    """
    submit = await java_client.post_json(
        f"{config.STORYBOARD_SVC_URL}/api/shots/video",
        {"dramaId": drama_id, "shotNo": shot["shotNo"], "prompt": shot["prompt"],
         "durationSec": shot["durationSec"]},
    )
    task_id = submit["taskId"]
    for _ in range(60):
        await asyncio.sleep(0.3)
        result = await java_client.get_json(
            f"{config.STORYBOARD_SVC_URL}/api/shots/video/{task_id}")
        if result["status"] == "SUCCESS":
            return {"shotNo": shot["shotNo"], "taskId": task_id,
                    "videoUrl": result["videoUrl"], "durationSec": shot["durationSec"]}
        if result["status"] == "NOT_FOUND":
            raise RuntimeError(f"video task {task_id} lost")
    raise TimeoutError(f"video task {task_id} timeout")


async def generate_voice(drama_id: str, scene: dict, dialogue: dict) -> dict:
    """配音合成：多角色 TTS + 时长回填（Mock）。"""
    await asyncio.sleep(0.15)
    return await java_client.post_json(
        f"{config.VOICE_SVC_URL}/api/voices/generate",
        {"dramaId": drama_id, "sceneId": scene["sceneId"],
         "character": dialogue["character"], "emotion": dialogue["emotion"],
         "text": dialogue["text"]},
    )


async def compose_drama(drama_id: str, shots: list, videos: list, voices: list) -> dict:
    """成片合成：音画对齐 + 字幕 + 转场（Mock FFmpeg）。"""
    return await java_client.post_json(
        f"{config.COMPOSE_SVC_URL}/api/compose",
        {"dramaId": drama_id, "shots": shots, "videos": videos, "voices": voices},
    )
